'use client'
import * as React from 'react'
import { Download, FileUp, Filter, Plus, RefreshCw, Save, Search, Trash2, Upload, Users } from 'lucide-react'
import { toast } from 'sonner'
import { ApexTable, type ApexTableColumn } from './ui/apex-table'

const PROFILE_COLUMNS = [
  ['emisCode','EMIS Code'],['studentId','Student ID'],['studentName','Student Name'],['fatherName','Father Name'],['gender','Gender'],['dateOfBirth','Date of Birth'],['bForm','B-Form'],['admissionNo','Admission No'],['admissionDate','Admission Date'],['className','Class'],['section','Section'],['shift','Shift'],['session','Session'],['status','Status'],['religion','Religion'],['motherTongue','Mother Tongue'],['disability','Disability'],['orphan','Orphan'],['minority','Minority'],['address','Address'],['village','Village'],['guardianName','Guardian Name'],['guardianCnic','Guardian CNIC'],['guardianPhone','Guardian Phone'],['district','District'],['tehsil','Tehsil'],['unionCouncil','Union Council'],['schoolName','School Name'],['previousSchool','Previous School'],['medium','Medium'],['transferStatus','Transfer Status'],['result','Result'],['remarks','Remarks'],['createdAt','Created'],['updatedAt','Updated'],
] as const
const EMPTY_PROFILE = Object.fromEntries(PROFILE_COLUMNS.filter(([key]) => key !== 'emisCode' && key !== 'createdAt' && key !== 'updatedAt').map(([key]) => [key, '']))
const classes = ['Kachi','1','2','3','4','5','6','7','8','9','10','11','12']
const field = (name: string, label: string, value: string, onChange: (value: string) => void, type = 'text') => <label key={name} className="text-xs text-gray-600">{label}<input className="apex-input mt-1" type={type} value={value} onChange={(e) => onChange(e.target.value)} /></label>

type Profile = Record<string, unknown> & { id: string }
type Props = { module: string; title: string; onNavigate: (m: string) => void }

export function StudentsMisPage({ module, title, onNavigate }: Props) {
  if (module === 'student-data-uploading') return <CsvUploadPage onNavigate={onNavigate} />
  if (module === 'enrolment-campaign-target') return <TargetPage title={title} onNavigate={onNavigate} />
  if (module === 'daily-students-enrolment') return <DailyPage title={title} onNavigate={onNavigate} />
  if (module === 'students-class-update') return <ClassUpdatePage title={title} onNavigate={onNavigate} />
  return <ProfilesPage title={title} onNavigate={onNavigate} />
}

function Layout({ title, onNavigate, children, actions }: { title: string; onNavigate: (m: string) => void; children: React.ReactNode; actions?: React.ReactNode }) {
  return <div className="t-Body-contentInner"><nav className="mb-2 flex items-center gap-1 text-xs text-gray-500"><button type="button" onClick={() => onNavigate('home')} className="hover:text-[#1565c0] hover:underline">Home</button><span>›</span><span>Students MIS</span><span>›</span><span className="font-medium text-[#1565c0]">{title}</span></nav><div className="mb-2 flex flex-wrap items-center justify-between gap-2"><h1 className="text-base font-semibold text-[#333] sm:text-lg">{title}</h1>{actions}</div>{children}</div>
}

function ProfilesPage({ title, onNavigate }: Omit<Props, 'module'>) {
  const [rows, setRows] = React.useState<Profile[]>([]); const [search, setSearch] = React.useState(''); const [className, setClassName] = React.useState(''); const [status, setStatus] = React.useState('ACTIVE'); const [loading, setLoading] = React.useState(true); const [showForm, setShowForm] = React.useState(false); const [editing, setEditing] = React.useState<Profile | null>(null)
  const load = React.useCallback(async () => { setLoading(true); const r = await fetch(`/api/students?search=${encodeURIComponent(search)}&className=${encodeURIComponent(className)}&status=${encodeURIComponent(status)}`, { cache: 'no-store' }); const d = await r.json(); if (r.ok) setRows(d.students || []); else toast.error(d.error || 'Unable to load students.'); setLoading(false) }, [search, className, status])
  React.useEffect(() => { void load() }, [load])
  const columns: ApexTableColumn[] = PROFILE_COLUMNS.map(([key, label]) => ({ key, label, sortable: true, mono: key === 'emisCode' || key === 'studentId', render: (row) => key === 'dateOfBirth' || key === 'admissionDate' || key === 'createdAt' || key === 'updatedAt' ? (row[key] ? new Date(String(row[key])).toLocaleDateString() : '') : String(row[key] ?? '') }))
  const download = () => { const csv = [PROFILE_COLUMNS.map(([, label]) => label).join(','), ...rows.map((r) => PROFILE_COLUMNS.map(([key]) => JSON.stringify(r[key] ?? '')).join(','))].join('\n'); const a = document.createElement('a'); a.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); a.download = 'student-profiles.csv'; a.click() }
  async function remove(row: Profile) { if (!window.confirm(`Delete ${String(row.studentName)}?`)) return; const r = await fetch(`/api/students/${row.id}`, { method: 'DELETE' }); if (r.ok) { toast.success('Student deleted.'); void load() } else toast.error('Unable to delete student.') }
  return <Layout title={title} onNavigate={onNavigate} actions={<><button className="apex-btn" onClick={download}><Download className="h-3.5 w-3.5" />Download</button><button className="apex-btn apex-btn--primary" onClick={() => { setEditing(null); setShowForm(true) }}><Plus className="h-3.5 w-3.5" />Add Student</button></>}><section className="apex-region"><div className="apex-region-header"><span className="flex items-center gap-2"><Users className="h-3.5 w-3.5" />Student Profiles</span><span className="text-xs text-gray-500">{rows.length} student(s)</span></div><div className="apex-region-body"><div className="mb-3 flex flex-wrap items-end gap-2"><div className="min-w-[180px] flex-1"><label className="apex-form-label">Search Report</label><input className="apex-input" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search student, father, ID, B-Form…" /></div><div><label className="apex-form-label">Class</label><select className="apex-select" value={className} onChange={(e) => setClassName(e.target.value)}><option value="">All classes</option>{classes.map((c) => <option key={c}>{c}</option>)}</select></div><div><label className="apex-form-label">Status</label><select className="apex-select" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All</option><option>ACTIVE</option><option>INACTIVE</option><option>TRANSFERRED</option></select></div><button className="apex-btn apex-btn--primary" onClick={() => void load()}><Search className="h-3.5 w-3.5" />Search</button><button className="apex-btn" onClick={() => void load()}><RefreshCw className="h-3.5 w-3.5" />Refresh</button></div>{loading ? <div className="py-10 text-center text-sm text-gray-500">Loading…</div> : <ApexTable columns={[{ key: '_actions', label: '', render: (row) => <span className="flex gap-2"><button className="text-[#1565c0] hover:underline" onClick={() => { setEditing(row as Profile); setShowForm(true) }}>Edit</button><button className="text-red-600" onClick={() => void remove(row as Profile)}><Trash2 className="h-3.5 w-3.5" /></button></span> }, ...columns]} rows={rows} emptyText="Student Profiles Data Not Found …!" maxHeight="62vh" />}</div></section>{showForm && <StudentForm student={editing} onClose={() => setShowForm(false)} onSaved={() => { setShowForm(false); void load() }} />}</Layout>
}

function StudentForm({ student, onClose, onSaved }: { student: Profile | null; onClose: () => void; onSaved: () => void }) { const [form, setForm] = React.useState<Record<string, string>>(() => Object.fromEntries(Object.keys(EMPTY_PROFILE).map((key) => [key, String(student?.[key] ?? '')]))); const [busy, setBusy] = React.useState(false); const set = (k: string, v: string) => setForm((x) => ({ ...x, [k]: v })); async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); const r = await fetch(student ? `/api/students/${student.id}` : '/api/students', { method: student ? 'PATCH' : 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); setBusy(false); if (!r.ok) { toast.error(d.error || 'Unable to save student.'); return } toast.success(student ? 'Student updated.' : 'Student added.'); onSaved() } return <div className="fixed inset-0 z-[70] grid place-items-center bg-black/40 p-4"><form onSubmit={submit} className="max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded border border-gray-300 bg-white p-4 shadow-xl"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold">{student ? 'Update Student Profile' : 'Add Student Profile'}</h2><button type="button" className="text-xl" onClick={onClose}>×</button></div><p className="mb-3 rounded bg-blue-50 px-3 py-2 text-xs text-blue-800">Your school EMIS code is applied automatically. School administrators cannot create or edit records belonging to another school.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(EMPTY_PROFILE).map(([key]) => { const label = PROFILE_COLUMNS.find(([k]) => k === key)?.[1] || key; return field(key, label, form[key] || '', (v) => set(key, v), key.toLowerCase().includes('date') ? 'date' : 'text') })}</div><div className="mt-4 flex justify-end gap-2"><button type="button" className="apex-btn" onClick={onClose}>Cancel</button><button className="apex-btn apex-btn--primary" disabled={busy}><Save className="h-3.5 w-3.5" />{busy ? 'Saving…' : 'Save Student'}</button></div></form></div> }

function CsvUploadPage({ onNavigate }: { onNavigate: (m: string) => void }) { const [file, setFile] = React.useState<File | null>(null); const [busy, setBusy] = React.useState(false); const [result, setResult] = React.useState(''); async function upload() { if (!file) return toast.error('Choose a CSV file first.'); setBusy(true); const text = await file.text(); const rows = parseCsv(text); const r = await fetch('/api/students', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ rows }) }); const d = await r.json(); setBusy(false); if (!r.ok) toast.error(d.error || 'Upload failed.'); else { setResult(`${d.count} student record(s) processed successfully.`); toast.success('CSV upload complete.'); } } return <Layout title="Student Data Uploading" onNavigate={onNavigate}><section className="apex-region"><div className="apex-region-header"><span className="flex items-center gap-2"><FileUp className="h-3.5 w-3.5" />CSV Upload Workflow</span><a className="apex-btn" href={`data:text/csv;charset=utf-8,${encodeURIComponent(PROFILE_COLUMNS.map(([, label]) => label).join(',') + '\n')}`} download="student-profile-template.csv"><Download className="h-3.5 w-3.5" />Template</a></div><div className="apex-region-body space-y-4"><div className="rounded border border-blue-100 bg-blue-50 p-3 text-sm text-blue-900"><strong>F / P / D / G codes:</strong> upload files may include F (female), P (present/active), D (disabled/disability), and G (guardian) values in the Gender, Status, Disability, and Guardian fields. The importer preserves those codes and upserts by Student ID within your school.</div><label className="block rounded border-2 border-dashed border-gray-300 p-8 text-center"><Upload className="mx-auto mb-2 h-8 w-8 text-gray-400" /><span className="block text-sm font-medium">Choose student CSV</span><span className="block text-xs text-gray-500">35-column Student Profiles template; maximum 2,000 rows</span><input type="file" accept=".csv,text/csv" className="mt-3" onChange={(e) => setFile(e.target.files?.[0] || null)} /></label>{file && <p className="text-sm text-gray-600">Selected: {file.name}</p>}<button className="apex-btn apex-btn--primary" disabled={!file || busy} onClick={() => void upload()}><Upload className="h-3.5 w-3.5" />{busy ? 'Uploading…' : 'Upload CSV'}</button>{result && <div className="rounded bg-green-50 p-3 text-sm text-green-800">{result}</div>}<div className="text-xs text-gray-500">All uploads are server-scoped to the authenticated school-admin account. EMIS Code from the CSV is ignored for school admins.</div></div></section></Layout> }

function parseCsv(text: string): Record<string, string>[] { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).filter(Boolean); if (!lines.length) return []; const parse = (line: string) => { const out: string[] = []; let cur = '', quoted = false; for (let i = 0; i < line.length; i++) { const ch = line[i]; if (ch === '"' && line[i + 1] === '"') { cur += '"'; i++ } else if (ch === '"') quoted = !quoted; else if (ch === ',' && !quoted) { out.push(cur.trim()); cur = '' } else cur += ch } out.push(cur.trim()); return out }; const headers = parse(lines[0]).map((x) => x.replace(/\s+/g, '').replace(/^EMISCode$/i, 'emisCode').replace(/^StudentID$/i, 'studentId').replace(/^StudentName$/i, 'studentName').replace(/^FatherName$/i, 'fatherName').replace(/^Class$/i, 'className')); return lines.slice(1).map((line) => Object.fromEntries(parse(line).map((value, i) => [headers[i], value]))) }

function TargetPage({ title, onNavigate }: Omit<Props, 'module'>) { const [rows, setRows] = React.useState<Record<string, unknown>[]>([]); const [form, setForm] = React.useState({ session: '2026-27', className: '1', target: '0', remarks: '' }); const load = async () => { const d = await (await fetch('/api/students/enrolment-target')).json(); setRows(d.targets || []) }; React.useEffect(() => { void load() }, []); async function save(e: React.FormEvent) { e.preventDefault(); const r = await fetch('/api/students/enrolment-target', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, target: Number(form.target) }) }); const d = await r.json(); if (!r.ok) toast.error(d.error); else { toast.success('Target saved.'); void load() } } return <Layout title={title} onNavigate={onNavigate}><section className="apex-region"><div className="apex-region-header">Enrolment Campaign Target</div><div className="apex-region-body"><form onSubmit={save} className="mb-4 grid gap-2 sm:grid-cols-4">{field('session','Session',form.session,(v) => setForm({ ...form, session: v }))}{field('className','Class',form.className,(v) => setForm({ ...form, className: v }))}{field('target','Target',form.target,(v) => setForm({ ...form, target: v }),'number')}<button className="apex-btn apex-btn--primary self-end"><Save className="h-3.5 w-3.5" />Save Target</button></form><ApexTable columns={[{ key: 'session', label: 'Session' },{ key: 'className', label: 'Class' },{ key: 'target', label: 'Target' },{ key: 'achieved', label: 'Achieved' },{ key: 'remarks', label: 'Remarks' }]} rows={rows} emptyText="Enrolment Campaign Target Data Not Found …!" /></div></section></Layout> }

function DailyPage({ title, onNavigate }: Omit<Props, 'module'>) { const [rows, setRows] = React.useState<Record<string, unknown>[]>([]); const [form, setForm] = React.useState({ enrolmentDate: new Date().toISOString().slice(0,10), className: '1', male: '0', female: '0', transgender: '0' }); const load = async () => { const d = await (await fetch('/api/students/daily-enrolment')).json(); setRows(d.enrolments || []) }; React.useEffect(() => { void load() }, []); async function save(e: React.FormEvent) { e.preventDefault(); const r = await fetch('/api/students/daily-enrolment', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ ...form, male: Number(form.male), female: Number(form.female), transgender: Number(form.transgender) }) }); const d = await r.json(); if (!r.ok) toast.error(d.error); else { toast.success('Daily enrolment saved.'); void load() } } return <Layout title={title} onNavigate={onNavigate}><section className="apex-region"><div className="apex-region-header">Daily Student Enrolment</div><div className="apex-region-body"><form onSubmit={save} className="mb-4 grid gap-2 sm:grid-cols-5">{field('enrolmentDate','Date',form.enrolmentDate,(v) => setForm({ ...form, enrolmentDate: v }),'date')}{field('className','Class',form.className,(v) => setForm({ ...form, className: v }))}{field('male','Male',form.male,(v) => setForm({ ...form, male: v }),'number')}{field('female','Female',form.female,(v) => setForm({ ...form, female: v }),'number')}<button className="apex-btn apex-btn--primary self-end"><Save className="h-3.5 w-3.5" />Save Daily Count</button></form><ApexTable columns={[{ key: 'enrolmentDate', label: 'Date' },{ key: 'className', label: 'Class' },{ key: 'male', label: 'Male' },{ key: 'female', label: 'Female' },{ key: 'transgender', label: 'F/P/D/G / Other' },{ key: 'total', label: 'Total' }]} rows={rows} emptyText="Daily Students Enrolment Data Not Found …!" /></div></section></Layout> }

function ClassUpdatePage({ title, onNavigate }: Omit<Props, 'module'>) { const [rows, setRows] = React.useState<Record<string, unknown>[]>([]); const [form, setForm] = React.useState({ studentId: '', toClass: '', effectiveDate: new Date().toISOString().slice(0,10), remarks: '' }); const load = async () => { const d = await (await fetch('/api/students/class-update')).json(); setRows(d.updates || []) }; React.useEffect(() => { void load() }, []); async function save(e: React.FormEvent) { e.preventDefault(); const r = await fetch('/api/students/class-update', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(form) }); const d = await r.json(); if (!r.ok) toast.error(d.error); else { toast.success('Class updated.'); setForm({ ...form, studentId: '' }); void load() } } return <Layout title={title} onNavigate={onNavigate}><section className="apex-region"><div className="apex-region-header">Students Class Update</div><div className="apex-region-body"><form onSubmit={save} className="mb-4 grid gap-2 sm:grid-cols-4">{field('studentId','Student ID',form.studentId,(v) => setForm({ ...form, studentId: v }))}{field('toClass','New Class',form.toClass,(v) => setForm({ ...form, toClass: v }))}{field('effectiveDate','Effective Date',form.effectiveDate,(v) => setForm({ ...form, effectiveDate: v }),'date')}<button className="apex-btn apex-btn--primary self-end"><Save className="h-3.5 w-3.5" />Update Class</button></form><ApexTable columns={[{ key: 'studentId', label: 'Student ID' },{ key: 'fromClass', label: 'From Class' },{ key: 'toClass', label: 'To Class' },{ key: 'effectiveDate', label: 'Effective Date' },{ key: 'remarks', label: 'Remarks' }]} rows={rows} emptyText="Students Class Update Data Not Found …!" /></div></section></Layout> }
